Core/src/main/java/dev/hypera/chameleon/core/Chameleon.java
Core/src/main/java/dev/hypera/chameleon/core/Plugin.java
Core/src/main/java/dev/hypera/chameleon/core/data/IPlatformData.java
Core/src/main/java/dev/hypera/chameleon/core/data/PluginData.java
Platforms/BungeeCord/src/main/java/dev/hypera/chameleon/bungeecord/BungeeCordChameleon.java
Platforms/BungeeCord/src/main/java/dev/hypera/chameleon/bungeecord/data/BungeeCordData.java
Platforms/Minestom/src/main/java/dev/hypera/chameleon/minestom/MinestomChameleon.java
Platforms/Minestom/src/main/java/dev/hypera/chameleon/minestom/data/MinestomData.java
Platforms/Spigot/src/main/java/dev/hypera/chameleon/spigot/SpigotChameleon.java
Platforms/Spigot/src/main/java/dev/hypera/chameleon/spigot/data/SpigotData.java
Platforms/Velocity/src/main/java/dev/hypera/chameleon/velocity/VelocityChameleon.java
Platforms/Velocity/src/main/java/dev/hypera/chameleon/velocity/data/VelocityData.java

Closes #17 
This is a breaking change, and requires Plugins to have a new method in their (core) main class, example:
```java
@Override
public @NotNull PluginData getData() {
return PluginData.builder().name("ChameleonProject").version("1.0.0").author("Me, Myself and I");
}
```
* This should be merged into `development`, however I forgot to set that when I created the pull request.

Add plugin and platform data

---

Core/src/main/java/dev/hypera/chameleon/core/Chameleon.java
Core/src/main/java/dev/hypera/chameleon/core/events/dispatch/EventManager.java
Core/src/main/java/dev/hypera/chameleon/core/managers/PluginManager.java
Core/src/main/java/dev/hypera/chameleon/core/objects/PlatformPlugin.java
Core/src/main/java/dev/hypera/chameleon/core/scheduling/Scheduler.java
Core/src/main/java/dev/hypera/chameleon/core/utils/logging/impl/ChameleonLoggerImpl.java
Core/src/main/resources/META-INF/CHAMELEON-LICENSE.txt
Platforms/BungeeCord/src/main/java/dev/hypera/chameleon/bungeecord/BungeeCordChameleon.java
Platforms/BungeeCord/src/main/java/dev/hypera/chameleon/bungeecord/events/BungeeCordEventHandler.java
Platforms/BungeeCord/src/main/java/dev/hypera/chameleon/bungeecord/managers/BungeeCordPluginManager.java
Platforms/BungeeCord/src/main/java/dev/hypera/chameleon/bungeecord/scheduling/BungeeCordScheduler.java
Platforms/Minestom/src/main/java/dev/hypera/chameleon/minestom/MinestomChameleon.java
Platforms/Minestom/src/main/java/dev/hypera/chameleon/minestom/events/MinestomEventHandler.java
Platforms/Minestom/src/main/java/dev/hypera/chameleon/minestom/manager/MinestomExtensionManager.java
Platforms/Minestom/src/main/java/dev/hypera/chameleon/minestom/managers/MinestomExtensionManager.java
Platforms/Minestom/src/main/java/dev/hypera/chameleon/minestom/scheduling/MinestomScheduler.java
Platforms/Spigot/src/main/java/dev/hypera/chameleon/spigot/SpigotChameleon.java
Platforms/Spigot/src/main/java/dev/hypera/chameleon/spigot/events/SpigotEventHandler.java
Platforms/Spigot/src/main/java/dev/hypera/chameleon/spigot/managers/SpigotPluginManager.java
Platforms/Spigot/src/main/java/dev/hypera/chameleon/spigot/scheduling/SpigotScheduler.java
Platforms/Velocity/src/main/java/dev/hypera/chameleon/velocity/VelocityChameleon.java
Platforms/Velocity/src/main/java/dev/hypera/chameleon/velocity/events/VelocityEventHandler.java
Platforms/Velocity/src/main/java/dev/hypera/chameleon/velocity/managers/VelocityPluginManager.java
Platforms/Velocity/src/main/java/dev/hypera/chameleon/velocity/scheduling/VelocityScheduler.java

This pull requests adds a PluginManager class and a Scheduler interface.
Example usage:
```java
boolean enabled = chameleon.getPluginManager().isPluginEnabled("LuckPerms");
```
```java
chameleon.getScheduler().runAsync(() -> {
});
```
This pull request also adds:
- More error handling
- `CHAMELEON-LICENSE.txt` 
- `Chameleon#getPlayers()`

Add PluginManager and Scheduler

---

annotations/src/main/java/dev/hypera/chameleon/annotations/Plugin.java
annotations/src/main/java/dev/hypera/chameleon/annotations/processing/generation/Generator.java
annotations/src/main/java/dev/hypera/chameleon/annotations/processing/generation/impl/bungeecord/BungeeCordGenerator.java
annotations/src/main/java/dev/hypera/chameleon/annotations/processing/generation/impl/minestom/MinestomGenerator.java
annotations/src/main/java/dev/hypera/chameleon/annotations/processing/generation/impl/spigot/SpigotGenerator.java
annotations/src/main/java/dev/hypera/chameleon/annotations/processing/generation/impl/velocity/VelocityGenerator.java
build.gradle.kts
core/src/main/java/dev/hypera/chameleon/core/Chameleon.java
core/src/main/java/dev/hypera/chameleon/core/ChameleonBootstrap.java
core/src/main/java/dev/hypera/chameleon/core/ChameleonPlugin.java
platform-bungeecord/src/main/java/dev/hypera/chameleon/platforms/bungeecord/BungeeCordChameleon.java
platform-bungeecord/src/main/java/dev/hypera/chameleon/platforms/bungeecord/BungeeCordChameleonBootstrap.java
platform-minestom/build.gradle.kts
platform-minestom/src/main/java/dev/hypera/chameleon/platforms/minestom/MinestomChameleon.java
platform-minestom/src/main/java/dev/hypera/chameleon/platforms/minestom/MinestomChameleonBootstrap.java
platform-spigot/build.gradle.kts
platform-spigot/src/main/java/dev/hypera/chameleon/platforms/spigot/SpigotChameleon.java
platform-spigot/src/main/java/dev/hypera/chameleon/platforms/spigot/SpigotChameleonBootstrap.java
platform-velocity/build.gradle.kts
platform-velocity/src/main/java/dev/hypera/chameleon/platforms/velocity/VelocityChameleon.java
platform-velocity/src/main/java/dev/hypera/chameleon/platforms/velocity/VelocityChameleonBootstrap.java

This pull request adds bootstrapping to Chameleon, this allows plugins to do things like runtime dependency loading before Chameleon is actually loaded.
**This breaks the current method of loading Chameleon**!
Chameleon now has to be loaded using: `<Platform>Chameleon#create(ChameleonPlugin.class, this, PluginData).load()`
Before this is merged, [Example #7](https://github.com/ChameleonFramework/Example/pull/7) should be merged.

feat!: Add bootstrapping

---

api/src/test/java/dev/hypera/chameleon/extensions/ExtensionTests.java
platform-velocity/src/main/java/dev/hypera/chameleon/platform/velocity/VelocityChameleon.java

Register Velocity event listener in the onEnable method to allow Chameleon to be loaded in the plugin's constructor.

fix(velocity): register event listener in onEnable

---

gradle/libs.versions.toml
platform-bungeecord/build.gradle.kts

**Summary**
Update `net.kyori:indra*` to `3.0.0` and adapt to breaking changes.
**Changes**
- Update `indra` to `3.0.0`
- `sonatypeSnapshots()` -> `sonatype.ossSnapshots()`
**Checklist**

chore(deps): update indra to v3

---

README.md

**Summary**
Add the MacStadium Open Source Developer logo to the README file.  
[MacStadium](https://www.macstadium.com/opensource) offers free Mac Minis for Open Source developers to build projects on MacOS. This would be helpful for Chameleon as we can run tests on the `main` branch using these powerful Mac Minis.  
The application for Chameleon was accepted, the account completion is currently pending.
**Changes**
- Add the MacStadium Open Source Developer logo to the Supporters section of the README file.
**Checklist**

chore: add MacStadium to README

---

platform-bukkit/src/main/java/dev/hypera/chameleon/platform/bukkit/BukkitChameleon.java
platform-bukkit/src/main/java/dev/hypera/chameleon/platform/bukkit/user/BukkitUserManager.java

**Summary**
Allows Chameleon plugins to load on Bukkit platforms.
**Changes**
* Prevent early usage of Adventure.
**Checklist**

fix(bukkit): prevent early usage of Adventure

---

platform-bungeecord/src/main/java/dev/hypera/chameleon/platform/bungeecord/user/BungeeCordUserManager.java

**Summary**
Fixes #202 
**Changes**
Make console sender a lazy initialiser.
**Checklist**

fix(bungeecord): make console sender a lazy initialiser

---

annotations/build.gradle.kts
annotations/src/main/java/dev/hypera/chameleon/annotations/processing/ChameleonAnnotationProcessor.java
annotations/src/main/java/dev/hypera/chameleon/annotations/processing/generation/folia/FoliaGenerator.java
api/src/main/java/dev/hypera/chameleon/platform/Platform.java
build-logic/build.gradle.kts
build-logic/src/main/kotlin/chameleon.base.gradle.kts
example/build.gradle.kts
example/src/main/java/dev/hypera/chameleon/example/ChameleonExample.java
gradle/libs.versions.toml
platform-bukkit/src/main/java/dev/hypera/chameleon/platform/bukkit/BukkitChameleon.java
platform-folia/build.gradle.kts
platform-folia/src/main/java/dev/hypera/chameleon/platform/folia/FoliaChameleon.java
platform-folia/src/main/java/dev/hypera/chameleon/platform/folia/FoliaChameleonBootstrap.java
platform-folia/src/main/java/dev/hypera/chameleon/platform/folia/extension/ChameleonFoliaExtension.java
platform-folia/src/main/java/dev/hypera/chameleon/platform/folia/platform/FoliaPlatform.java
platform-folia/src/main/java/dev/hypera/chameleon/platform/folia/platform/FoliaPluginManager.java
platform-folia/src/main/java/dev/hypera/chameleon/platform/folia/platform/objects/FoliaPlugin.java
platform-folia/src/main/java/dev/hypera/chameleon/platform/folia/scheduler/FoliaScheduler.java

**Summary**
Adds Folia support to Chameleon
**Changes**
* Use Paper's plugin loader.
* Use Paper's plugin management API.
* Use Folia's scheduling API.
**Checklist**

feat: add Folia Support

---

.github/workflows/gradle.yml
.github/workflows/publish.yml

**Summary**
Add merge group support to `gradle.yml` workflow, improve speed of `Determine version` step in `publish.yml` workflow.
**Changes**
- Add support for `merge_group` event in `gradle.yml` workflow
- Improve the speed of `Determine version` step in `publish.yml` workflow by using `grep` instead of running the Gradle wrapper.
**Checklist**

ci: add support for merge groups, improve performance of publish step

---

SECURITY.md
api/src/main/java/dev/hypera/chameleon/event/AbstractCancellable.java
api/src/main/java/dev/hypera/chameleon/event/Cancellable.java
api/src/main/java/dev/hypera/chameleon/event/EventBusImpl.java
api/src/main/java/dev/hypera/chameleon/event/common/UserChatEvent.java
api/src/main/java/dev/hypera/chameleon/event/common/UserConnectEvent.java
api/src/test/java/dev/hypera/chameleon/event/EventBusTests.java
build.gradle.kts

**Summary**
Move the `Cancellable` interface, and the `AbstractCancellable` abstract implementation to the `dev.hypera.chameleon.event` package.
They are currently in `dev.hypera.chameleon.event.cancellable`, when there is really no reason to separate them.
**Changes**
- Move the `Cancellable` interface to `dev.hypera.chameleon.event`
- Move the `AbstractCancellable` class to `dev.hypera.chameleon.event`
- Bump the version to `0.18.0-SNAPSHOT`
**Checklist**
**This pull request contains breaking changes.**

refactor(api)!: move Cancellable to the event package

---

.github/renovate.json5

**Summary**
Make Renovate ignore experimental snapshots for the Spigot API (`org.spigotmc:spigot-api`)
**Changes**
- Add Renovate package rule to disallow Spigot API versions ending with `-experimental-SNAPSHOT`
**Checklist**

chore: make renovate ignore experimental Spigot API snapshots

---

.github/release.yml
.github/workflows/release.yml
CONTRIBUTING.md

**Summary**
Reduce `release` job's permissions to only `contents: read`.
Previously this job required `contents: write` to create releases, however as the job now uses
a @hypera-bot token to create releases, this is no longer required.
**Changes**
- Update `release.yml`/`release` to only have required permissions.
- Update `CONTRIBUTING.md` to allow commit scope to use workflow names when type is `ci`.
**Checklist**

ci(release): reduce permissions to contents read

---

api/src/main/java/dev/hypera/chameleon/platform/PlatformPlugin.java
platform-bukkit/src/main/java/dev/hypera/chameleon/platform/bukkit/platform/objects/BukkitPlugin.java
platform-bungeecord/src/main/java/dev/hypera/chameleon/platform/bungeecord/platform/objects/BungeeCordPlugin.java
platform-folia/src/main/java/dev/hypera/chameleon/platform/folia/platform/objects/FoliaPlugin.java
platform-nukkit/src/main/java/dev/hypera/chameleon/platform/nukkit/platform/plugin/NukkitPlugin.java
platform-sponge/src/main/java/dev/hypera/chameleon/platform/sponge/platform/plugin/SpongePlugin.java
platform-velocity/src/main/java/dev/hypera/chameleon/platform/velocity/platform/objects/VelocityPlugin.java

**Summary**
Fixes #291
Renamed the working directory of the platform plugin.
**Changes**
PlatformPlugin
BukkitPlugin
BungeeCordPlugin
FoliaPlugin
NukkitPlugin
SpongePlugin
VelocityPlugin
**Checklist**

fix(api): rename PlatformPlugin#getDataFolder to #getDataDirectory

---

.github/workflows/gradle.yml
.github/workflows/release.yml

**Summary**
Adds Dependency Graph submission to the `gradle.yml` workflow.
This adds a separate step as submission requires `contents: write` permissions, and should only run on pushes.
Resolves #301
**Changes**
- Add Dependency Graph submission to `gradle.yml` workflow
- Rename `Set up Indra` step in `release.yml` to `Prepare for Release`
**Checklist**
conduct](https://github.com/ChameleonFramework/.github/blob/main/CODE_OF_CONDUCT.md).

ci(gradle): submit dependency graph (resolves #301)

---

platform-bungeecord/build.gradle.kts

**Summary**
BungeeCord made a breaking change in a snapshot build.
`net.md-5:bungeecord-protocol` now requires `com.mojang:brigadier`:
https://github.com/SpigotMC/BungeeCord/commit/0f5f09b6c5f073130515c8cd435541c5c68bcba8#diff-e525b362f47a48b0098711fe063c8200a195c5a9bd98f2bf02e25926b83c4caa
`com.mojang:brigadier` is available from `https://libraries.minecraft.net/`.
Previously, (a fork of) brigadier would be resolved from Sonatype Snapshots,
however md-5 seemingly updated brigadier, and now `bungeecord-protocol` depends on Minecraft's
Maven repository.
**Changes**
- Add `https://libraries.minecraft.net/` repository to the `platform-bungeecord` module.
**Checklist**

fix(bungeecord): brigadier not being resolved

---

.github/workflows/release.yml

**Summary**
Add `GITHUB_RELEASE_TOKEN` secret to the `release.yml` workflow.
This secret is required by the `gradle-release.yml` workflow that is called, and is used to create the GitHub release.
**Changes**
- Add `GITHUB_RELEASE_TOKEN` secret to `release.yml`.
**Checklist**

ci(release): fix release token not being set

---

api/build.gradle.kts
platform-bukkit/build.gradle.kts
platform-nukkit/build.gradle.kts

**Summary**
Internally, Chameleon uses the legacy and GSON Adventure component
serializers. However, as they are not a part of the API nor are needed
by end-users, they should not be exposed as `api` dependencies.
Additionally, the legacy serializer is only required by the Bukkit and
Nukkit platform implementations, and should not be a dependency of the
API module.
**Changes**
- Remove dependence on legacy component serializer from API module
- Add dependence on legacy component serializer to Bukkit and Nukkit modules
- Make component serializer dependencies `implementation` to avoid exposing them to end-users.
**Checklist**

build!: cleanup adventure serializer dependence

---

api/src/main/java/dev/hypera/chameleon/ChameleonBootstrap.java
api/src/main/java/dev/hypera/chameleon/event/EventBus.java
api/src/main/java/dev/hypera/chameleon/event/EventBusImpl.java
api/src/main/java/dev/hypera/chameleon/event/EventConsumer.java
api/src/main/java/dev/hypera/chameleon/event/EventSubscriber.java
api/src/main/java/dev/hypera/chameleon/event/EventSubscriberImpl.java
api/src/test/java/dev/hypera/chameleon/event/EventBusTests.java

**Summary**
Add `EventBus.ExceptionHandler`, allowing developers to define custom event exception handling logic.
**Changes**
- Add `EventConsumer` interface that allows exceptions to be thrown.
- Add `EventBus.ExceptionHandler` interface that handles exceptions caught during dispatch.
- Add `ChameleonBootstrap#withEventExceptionHandler(EventBus.ExceptionHandler)`
- **Breaking**: Change `EventSubscriber.Builder#handler(Consumer)` to `EventSubscriber.Builder#handler(EventConsumer)`
- Make `EventSubscriber` extend `EventConsumer`
- **Breaking**: Change `EventBus#subscribe(Class, EventSubscriber)` to `EventBus#subscribe(Class, EventConsumer)`
- Add `EventBus#setExceptionHandler(ExceptionHandler)`
**Checklist**
**This pull request contains breaking changes.**

feat(event)!: add event bus exception handler

---

.github/workflows/gradle.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml

**Summary**
Update the GitHub Actions workflows to adjust for changes in `HyperaDev/actions` introduced by https://github.com/HyperaDev/actions/pull/27/
**Changes**
- Run Gradle with Java 21
- Use strings for `java_version` in Gradle workflows
- Set `codecov_enabled: true`, as it now defaults to `false`
- Set name to `Gradle` for all workflows, allowing workflows to appear as `Gradle / Build / Build`, `Gradle / Snapshot / Publish`, etc
- Do not run the `gradle.yml` (build) workflow on release branches
- Tidy up
**Checklist**

ci: adjust for changes in reusable workflows

---

.github/workflows/gradle.yml

**Summary**
Add `CODECOV_TOKEN` secret to `gradle.yml` workflow.
This is needed because HyperaDev/actions now uses `codecov/codecov-action@v4.0.0`.
Related: https://github.com/HyperaDev/actions/pull/30
**Changes**
- Add `CODECOV_TOKEN` secret to the `gradle.yml` workflow.
**Checklist**

ci(gradle): add codecov token secret

---

.github/workflows/gradle.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml

**Summary**
Add concurrency groups to the GitHub Actions workflows.
Previously these were done in the reusable workflows, however this is no longer the case as of https://github.com/HyperaDev/actions/pull/31.
**Changes**
- Add concurrency groups to each GitHub Actions workflow.
**Checklist**

ci: add concurrency groups

---

api/src/main/java/dev/hypera/chameleon/util/internal/ChameleonProperty.java
platform-velocity/src/main/java/dev/hypera/chameleon/platform/velocity/event/VelocityEventDispatcher.java

**Summary**
Add `ChameleonProperty.PREVENT_CHAT_PROTOCOL_ERRORS` which can be set to `false` to prevent Chameleon from preventing chat events from being cancelled or modified for players with protocol version 760 or newer.
Plugins like [SignedVelocity](https://github.com/4drian3d/SignedVelocity) can be used to workaround players being kicked if these events are cancelled or modified, so we want to allow plugins to change this behaviour if they wish.
**Changes**
- Add `ChameleonProperty.PREVENT_CHAT_PROTOCOL_ERRORS` property (naming can be changed)
**Checklist**

feat(velocity): add property to change behaviour of chat cancel/modification

---

api/src/main/java/dev/hypera/chameleon/event/common/UserConnectEvent.java
api/src/main/java/dev/hypera/chameleon/event/proxy/ProxyUserConnectedEvent.java
api/src/main/java/dev/hypera/chameleon/event/proxy/ProxyUserServerConnectedEvent.java
platform-bungeecord/src/main/java/dev/hypera/chameleon/platform/bungeecord/event/BungeeCordEventDispatcher.java
platform-velocity/src/main/java/dev/hypera/chameleon/platform/velocity/event/VelocityEventDispatcher.java

**Summary**
Add `ProxyUserConnectedEvent` which is dispatched once the user has successfully connected to the proxy and has been connected to a server.
Rename `ProxyUserSwitchEvent` to `ProxyUserServerConnectedEvent`, as the new naming makes a lot more sense in the context of how the proxy works and when the event is dispatched.
**Changes**
- Add `ProxyUserConnectedEvent`
- Refactor `ProxyUserSwitchEvent` into `ProxyUserServerConnectedEvent` (`#getFrom()` -> `#getPreviousServer()`, `#getTo()` -> `#getServer()`)
- Improve javadoc in `UserConnectEvent`
**Checklist**
**This pull request contains breaking changes.**

refactor(event)!: add ProxyUser{,Server}ConnectedEvent

---

example/build.gradle.kts
gradle/libs.versions.toml

**Summary**
The Gradle shadow plugin by johnrengelman is currently unmaintained, and does not currently support the latest versions of Gradle.
There have been discussions regarding the future of the plugin, however nothing has been acted upon currently: johnrengelman/shadow#908
This fork appears to be the most supported and best maintained fork, and has been suggested as the replacement for the original shadow plugin.
Fixes #414
Related to #410
**Changes**
- Use https://github.com/Goooler/shadow instead of https://github.com/johnrengelman/shadow
- Use `gradle/libs.version.toml` for shadow plugin
**Checklist**

build: switch to Goooler/shadow fork
